name: Run Python Script

on:
  push:
    branches:
      - Pyhton_TFI  # Atau nama branch yang sesuai
  schedule:
    - cron: '0 * * * *'  # Menjalankan setiap jam pada menit ke-0 (sesuaikan jika perlu)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Ganti dengan versi Python yang kamu gunakan

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        python script-bot_TFI.py  # Ganti dengan nama file Python kamu
